git add ArtGallery/*.config -f
git add ArtGallery/*.cs -f
git add ArtGallery/*.xml -f
git add ArtGallery/*.csproj -f
git add ArtGallery/*.txt -f
git add ArtGallery/*.aspx -f
git add ArtGallery/*.html -f
git add ArtGallery/*.asax -f
git add ArtGallery/*.ico -f
git add ArtGallery/*.Master -f
git add ArtGallery/*.xsd -f
git add ArtGallery/*.wsdl -f
git add ArtGallery/*.map -f
git add ArtGallery/*.datasource -f
git add ArtGallery/*.css -f
git add ArtGallery/*.js -f
git add ArtGallery/*.big -f
git add ArtGallery/*.settings -f
git add ArtGallery/Images/*.* -f
git add ArtGallery/*.ashx -f
git add ArtGallery/*.xsc -f
git add ArtGallery/*.xss -f
git add ArtGallery/*.skin -f
git add ArtGallery/*.resx -f