//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.HelpText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this button will add a row to the bottom of the table allowing you to enter a new reproduction..
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When checked this indicates that the original art work is available for sale. If not checked, but there are one or reproductions entered, then where the price is usual displayed, the phrase &quot;Original art work is not available for sale&quot; is displayed. If this not checked and there are not reproductions, then this art work is not display in any public menu.&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this link removes the values you have entered and restores the screen to it original state..
        /// </summary>
        internal static string CancelInsert {
            get {
                return ResourceManager.GetString("CancelInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this link discards the changes you made to this row..
        /// </summary>
        internal static string CancelInsertGird {
            get {
                return ResourceManager.GetString("CancelInsertGird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this link discards the change made to the item above and restores these items to their original values..
        /// </summary>
        internal static string CancelUpdate {
            get {
                return ResourceManager.GetString("CancelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this link discards the changes you entered in this row..
        /// </summary>
        internal static string CancelUpdateGrid {
            get {
                return ResourceManager.GetString("CancelUpdateGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this link will delete the gallery from the database. This can fail if there are pictures still in the gallery..
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this link deletes this reproduction record and redraws the table with this record removed..
        /// </summary>
        internal static string DeleteGrid {
            get {
                return ResourceManager.GetString("DeleteGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this link is selected, the record for this picture and its reproduction are removed from the database. That actual picture image file remains on the server and he be reused in another gallery. When selected, this link returns you back to the home page..
        /// </summary>
        internal static string DeletePicture {
            get {
                return ResourceManager.GetString("DeletePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter additional information about this art work here. This information is displayed on the Picture and Search Result pages. If this field is left blank, the description line is removed from these pages on the Picture and Search Result pages.&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this link allows you to edit this reproduction record.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is a framed piece, put the frame description here; otherwise enter as unframed. This value is displayed on the Picture and Search Result pages. &lt;br/&gt;&lt;br/&gt;Changes on this screen made will not be permanent until you select the Update link below..
        /// </summary>
        internal static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When not checked, the Gallery will not appear in the list of Galleries visible to the public. Leave unchecked until the gallery is ready.&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new gallery) below..
        /// </summary>
        internal static string GalleryAvailable {
            get {
                return ResourceManager.GetString("GalleryAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the text that will appear on the top of the Gallery Description Page. &lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new gallery) below..
        /// </summary>
        internal static string GalleryDescription {
            get {
                return ResourceManager.GetString("GalleryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the text that will appear in the Galleries menu.&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new gallery) below..
        /// </summary>
        internal static string GalleryMenu {
            get {
                return ResourceManager.GetString("GalleryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gallery where the art work is displayed. You can move an art work to another gallery by selecting a different gallery from the list&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string GalleryName {
            get {
                return ResourceManager.GetString("GalleryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the dollar amount added to the shipping charge that is independent of distance but may include your cost of packaging the art work to protect it during shipping. This handling charge will be displayed by PayPal on the Buy Now page.&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string Handling {
            get {
                return ResourceManager.GetString("Handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For both a framed and unframed art work,  the height should be the unframed height. You can give a more details about the overall dimensions in the description below for a framed piece. This value is displayed on the Picture and Search Result pages.&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this link inserts a new record into the database. Failure to select to link will mean that your changes will not be saved..
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this link saves the new reproduction record..
        /// </summary>
        internal static string InsertGrid {
            get {
                return ResourceManager.GetString("InsertGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select Local Pickup if you reside or visiting the Pittsburgh, PA area and wish to come to the artist studio to pickup the art work. In this case there would be no shipping or handling charges..
        /// </summary>
        internal static string LocalPickup {
            get {
                return ResourceManager.GetString("LocalPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the media used to created this art work here. This information will be displayed on the Picture and Search pages.&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pages.&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string MetaTagsPicture {
            get {
                return ResourceManager.GetString("MetaTagsPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These note are only displayed on the screen and not displayed on any other page of this site.&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weigth of packing used to safely ship the artwork. This is added to the weight of the artwork to determine the shipping costs.&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string PackingWeight {
            get {
                return ResourceManager.GetString("PackingWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name of the image file containing the image to display. Normally this text box is filled in automatically when the image is uploaded from your computer. &lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string PictureFile {
            get {
                return ResourceManager.GetString("PictureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title of the art work here. The title appears in menus, the Picture page, Search Result page and as the item name in PayPal on the Buy Now page and PayPal correspondence. &lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string PictureTitle {
            get {
                return ResourceManager.GetString("PictureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the price for the original art work here. The price should be in the currency selected on the PayPal page. Please do not enter separators between thousands. This is not the price of geclee prints made from the original, those prices should be entered below. &lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framed pieces are shipped in StrongBox packaging which cost between $50 to $150 depending on the size of the piece and adds weights 3 to 7 pounds to the shipping. The frames themselves weight between 2 and 10 pounds. We can unframe the art work and ship it to you so you can frame it. The shipping container for unframed art work costs about $10 (dependent on size) and adds about 2 pounds to the shipping costs. Unframed pieces weight less than a pound..
        /// </summary>
        internal static string Unframed {
            get {
                return ResourceManager.GetString("Unframed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this link updates the databases you have just made on this screen. Failure to select this link means that all changes you made will be lost..
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this link will restore the values on the page to their values since the last update or if this screen has not been updated, then the values when the screen was originally displayed..
        /// </summary>
        internal static string UpdateCancel {
            get {
                return ResourceManager.GetString("UpdateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this link saves the changes you made to this row..
        /// </summary>
        internal static string UpdateGrid {
            get {
                return ResourceManager.GetString("UpdateGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the total weight of the piece including the frame and the packing used to protect the art work during shipping. This value is used to by PayPal to determine the shipping costs. This value is displayed on the Picture and Search Result pages.&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For both a framed and unframed art work, the width should be the unframed width. You can give a more details about the overall dimensions in the description below for a framed piece. This value is displayed on the Picture and Search Result pages. Changes made will not be permanent until you select the Update link below.&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the year when this art work was completed. This will be displayed on the picture page and as part of the copyright notice.&lt;br/&gt;&lt;br/&gt;Changes made on this screen will not be permanent until you select the Update link (or Insert Link for a new picture) below..
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
